#!./node/node

const cli = require('cli');

const server = require('./server');

cli.enable('version').enable('status');

cli.parse(server.opts);

cli.main((args, opts) => {
	server.load(args, opts);
});
